# Generated by Django 5.2.1 on 2025-06-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_student_classes_student_class_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='name',
            new_name='school_name',
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='academic_year',
            field=models.IntegerField(default=2025, null=True),
        ),
    ]
